//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVDEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GVDEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap analyze {
            get {
                object obj = ResourceManager.GetObject("analyze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap app_settings {
            get {
                object obj = ResourceManager.GetObject("app-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap colors {
            get {
                object obj = ResourceManager.GetObject("colors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap create {
            get {
                object obj = ResourceManager.GetObject("create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap debugging {
            get {
                object obj = ResourceManager.GetObject("debugging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap desktop {
            get {
                object obj = ResourceManager.GetObject("desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap environment {
            get {
                object obj = ResourceManager.GetObject("environment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bolo zadané neplatné číslo..
        /// </summary>
        public static string FAppSettings_Bolo_zadané_neplatné_číslo {
            get {
                return ResourceManager.GetString("FAppSettings_Bolo_zadané_neplatné_číslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Niektoré vykonané zmeny sa prejavia po reštarte programu. 
        ///
        ///Reštartovať program teraz?.
        /// </summary>
        public static string FAppSettings_bSave_Click_Niektoré_zmeny_sa_prejavia_až_po_reštarte_programu {
            get {
                return ResourceManager.GetString("FAppSettings_bSave_Click_Niektoré_zmeny_sa_prejavia_až_po_reštarte_programu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybrali ste typ debugovania, ktorý nie je určený pre bežných používateľov.  To môže viesť k neočakávaným následkom.
        ///
        ///Naozaj chcete použiť tento typ debugovania?.
        /// </summary>
        public static string FAppSettings_cbDebugModeGUI_SelectedIndexChanged_Not_For_All_Users {
            get {
                return ResourceManager.GetString("FAppSettings_cbDebugModeGUI_SelectedIndexChanged_Not_For_All_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stlačte klávesovú skratku pre priradenie ku príkazu..
        /// </summary>
        public static string FAppSettings_lShortcutHelp1 {
            get {
                return ResourceManager.GetString("FAppSettings_lShortcutHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Neplatná klávesová skratka. Stlačte inú..
        /// </summary>
        public static string FAppSettings_lShortcutHelp2 {
            get {
                return ResourceManager.GetString("FAppSettings_lShortcutHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zmeny sa prejavia po reštarte programu..
        /// </summary>
        public static string FAppSettings_Zmeny_sa_prejavia_po_reštarte_programu {
            get {
                return ResourceManager.GetString("FAppSettings_Zmeny_sa_prejavia_po_reštarte_programu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný E-mail je neplatný..
        /// </summary>
        public static string FBugReport_E_mail_je_neplatný {
            get {
                return ResourceManager.GetString("FBugReport_E_mail_je_neplatný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný E-mail nebol zadaný..
        /// </summary>
        public static string FBugReport_E_mail_nebol_zadaný {
            get {
                return ResourceManager.GetString("FBugReport_E_mail_nebol_zadaný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný E-mail sa nepodarilo odoslať: .
        /// </summary>
        public static string FBugReport_E_mail_sa_nepodarilo_odoslať {
            get {
                return ResourceManager.GetString("FBugReport_E_mail_sa_nepodarilo_odoslať", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Obsah správy nebol zadaný..
        /// </summary>
        public static string FBugReport_Obsah_správy_nebol_zadaný {
            get {
                return ResourceManager.GetString("FBugReport_Obsah_správy_nebol_zadaný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Čas príchodu je neskôr ako čas odchodu..
        /// </summary>
        public static string FEditTrain_bSave_Click_Čas_príchodu_je_neskôr_ako_čas_odchodu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Čas_príchodu_je_neskôr_ako_čas_odchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nesprávny formát času odchodu..
        /// </summary>
        public static string FEditTrain_bSave_Click_Nesprávny_formát_času_odchodu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Nesprávny_formát_času_odchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nesprávny formát času príchodu..
        /// </summary>
        public static string FEditTrain_bSave_Click_Nesprávny_formát_času_príchodu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Nesprávny_formát_času_príchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nie je vybratá koľaj..
        /// </summary>
        public static string FEditTrain_bSave_Click_Nie_je_vybratá_koľaj {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Nie_je_vybratá_koľaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Varianta tohto vlaku nemôže byť -1, pretože sa v zozname vlakov nachádza vlak/y s podobnými vlastnosťami..
        /// </summary>
        public static string FEditTrain_bSave_Click_Varianta_tohto_vlaku_nemôže_byť_Minus_1 {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Varianta_tohto_vlaku_nemôže_byť_Minus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vlak nemá zadanú žiadnu stanicu..
        /// </summary>
        public static string FEditTrain_bSave_Click_Vlak_nemá_zadanú_žiadnu_stanicu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Vlak_nemá_zadanú_žiadnu_stanicu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraná varianta vlaku sa už používa pri inom vlaku..
        /// </summary>
        public static string FEditTrain_bSave_Click_Vybraná_varianta_vlaku_sa_už_používa_pri_inom_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Vybraná_varianta_vlaku_sa_už_používa_pri_inom_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Začiatok platnosti musí skôr ako koniec platnosti..
        /// </summary>
        public static string FEditTrain_bSave_Click_Začiatok_platnosti_musí_skôr_ako_koniec_platnosti {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Začiatok_platnosti_musí_skôr_ako_koniec_platnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadajte číslo vlaku..
        /// </summary>
        public static string FEditTrain_bSave_Click_Zadajte_číslo_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Zadajte_číslo_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Číslo vlaku sa zhoduje s iným vlakom a preto bude aj jeho radenie priradené k tomuto vlaku (Doteraz upravené radenie sa vymaže)..
        /// </summary>
        public static string FEditTrain_Číslo_vlaku_sa_zhoduje_s_iným_vlakom_a_preto_bude_aj_jeho_radenie_priradené_k_tomuto_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_Číslo_vlaku_sa_zhoduje_s_iným_vlakom_a_preto_bude_aj_jeho_radenie_prir" +
                        "adené_k_tomuto_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dátumové obmedzenie radenia obsahuje chybu: .
        /// </summary>
        public static string FEditTrain_DateRem_radenia_obsahuje_chybu {
            get {
                return ResourceManager.GetString("FEditTrain_DateRem_radenia_obsahuje_chybu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dátumové obmedzenie tohto vlaku zasahuje do vlaku {0} {1} {2} v rozmedzí 
        ///&quot;{3}&quot;.
        ///
        ///Upraviť dátumové obmedzenie popísaného vlaku?.
        /// </summary>
        public static string FEditTrain_DateRem_zasahuje_do_ineho_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_DateRem_zasahuje_do_ineho_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duplikovať vlak.
        /// </summary>
        public static string FEditTrain_FEditTrain_Duplikovať_vlak {
            get {
                return ResourceManager.GetString("FEditTrain_FEditTrain_Duplikovať_vlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pridať.
        /// </summary>
        public static string FEditTrain_FEditTrain_Pridať {
            get {
                return ResourceManager.GetString("FEditTrain_FEditTrain_Pridať", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pridať vlak.
        /// </summary>
        public static string FEditTrain_FEditTrain_Pridať_vlak {
            get {
                return ResourceManager.GetString("FEditTrain_FEditTrain_Pridať_vlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nebolo zadané radenie vlaku..
        /// </summary>
        public static string FEditTrain_Nebolo_zadané_radenie_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_Nebolo_zadané_radenie_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nezadaný čas odchodu..
        /// </summary>
        public static string FEditTrain_Nezadaný_čas_odchodu {
            get {
                return ResourceManager.GetString("FEditTrain_Nezadaný_čas_odchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nezadaný čas príchodu..
        /// </summary>
        public static string FEditTrain_Nezadaný_čas_príchodu {
            get {
                return ResourceManager.GetString("FEditTrain_Nezadaný_čas_príchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tento vlak nemá iné varianty a preto mu bude varianta nastavená na hodnotu -1..
        /// </summary>
        public static string FEditTrain_Tento_vlak_nemá_iné_varianty_a_preto_mu_bude_varianta_nastavená_na_hodnotu_Minus_1 {
            get {
                return ResourceManager.GetString("FEditTrain_Tento_vlak_nemá_iné_varianty_a_preto_mu_bude_varianta_nastavená_na_hod" +
                        "notu_Minus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Začiatok platnosti radenia je neskôr ako jeho koniec..
        /// </summary>
        public static string FEditTrain_Začiatok_platnosti_radenia_je_neskôr_ako_jeho_koniec {
            get {
                return ResourceManager.GetString("FEditTrain_Začiatok_platnosti_radenia_je_neskôr_ako_jeho_koniec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadané dátumové obmedzenie radenia sa prekrýva s iným v období {0}..
        /// </summary>
        public static string FEditTrain_Zadané_dátumové_obmedzenie_radenia_sa_prekrýva_s_iným_v_období {
            get {
                return ResourceManager.GetString("FEditTrain_Zadané_dátumové_obmedzenie_radenia_sa_prekrýva_s_iným_v_období", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný súbor neexistuje..
        /// </summary>
        public static string FELISOptions_Zadaný_súbor_neexistuje {
            get {
                return ResourceManager.GetString("FELISOptions_Zadaný_súbor_neexistuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Iba jeden jazyk môže byť hlavný..
        /// </summary>
        public static string FGlobalSettings_bLanguageAdd_Click_Iba_1_jazyk_môže_byť_hlavný {
            get {
                return ResourceManager.GetString("FGlobalSettings_bLanguageAdd_Click_Iba_1_jazyk_môže_byť_hlavný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný typ vlaku sa už v zozname nachádza..
        /// </summary>
        public static string FGlobalSettings_Click_Zadaný_typ_vlaku_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Click_Zadaný_typ_vlaku_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kľúč jazyka sa nezhoduje so žiadnym jazykom nacházajúci sa v zvukovej banke..
        /// </summary>
        public static string FGlobalSettings_Kľúč_jazyka_sa_nezhoduje_so_žiadnym_jazykom_nacházajúci_sa_v_zvukovej_banke {
            get {
                return ResourceManager.GetString("FGlobalSettings_Kľúč_jazyka_sa_nezhoduje_so_žiadnym_jazykom_nacházajúci_sa_v_zvuk" +
                        "ovej_banke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Maximálny počet typov vlakov tohto druhu je 9..
        /// </summary>
        public static string FGlobalSettings_Maximálny_počet_typov_vlakov_tohto_druhu_je_9 {
            get {
                return ResourceManager.GetString("FGlobalSettings_Maximálny_počet_typov_vlakov_tohto_druhu_je_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Číslo {0} nie je v intervale X &gt;= 0 a zároveň X &lt;= 480..
        /// </summary>
        public static string FGlobalSettings_Meskanie_CisloNieJeVIntervale {
            get {
                return ResourceManager.GetString("FGlobalSettings_Meskanie_CisloNieJeVIntervale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Naozaj chcete odstrániť tento grafikon ?.
        /// </summary>
        public static string FGlobalSettings_Naozaj_chcete_odstrániť_tento_grafikon {
            get {
                return ResourceManager.GetString("FGlobalSettings_Naozaj_chcete_odstrániť_tento_grafikon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Názov tejto audio linky už existuje..
        /// </summary>
        public static string FGlobalSettings_Názov_tejto_audio_linky_už_existuje {
            get {
                return ResourceManager.GetString("FGlobalSettings_Názov_tejto_audio_linky_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nebola zadaná skratka typu vlaku..
        /// </summary>
        public static string FGlobalSettings_Nebola_zadaná_skratka_typu_vlaku {
            get {
                return ResourceManager.GetString("FGlobalSettings_Nebola_zadaná_skratka_typu_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Neboli vyplnené všetky polia..
        /// </summary>
        public static string FGlobalSettings_Neboli_vyplnené_všetky_polia {
            get {
                return ResourceManager.GetString("FGlobalSettings_Neboli_vyplnené_všetky_polia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Táto hodnota sa už v zozname nachádza..
        /// </summary>
        public static string FGlobalSettings_Táto_hodnota_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Táto_hodnota_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraný typ vlaku sa už v zozname nachádza..
        /// </summary>
        public static string FGlobalSettings_Vybraný_typ_vlaku_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Vybraný_typ_vlaku_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný jazyk sa sa už v zozname nachádza..
        /// </summary>
        public static string FGlobalSettings_Zadaný_jazyk_sa_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Zadaný_jazyk_sa_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nie sú zadané údaje pre import..
        /// </summary>
        public static string FImportData_Nie_sú_zadané_údaje_pre_import {
            get {
                return ResourceManager.GetString("FImportData_Nie_sú_zadané_údaje_pre_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap find_replace {
            get {
                object obj = ResourceManager.GetObject("find_replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Koľaj .
        /// </summary>
        public static string FLocalSettings_Koľaj_ {
            get {
                return ResourceManager.GetString("FLocalSettings_Koľaj_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nástupište .
        /// </summary>
        public static string FLocalSettings_Nástupište_ {
            get {
                return ResourceManager.GetString("FLocalSettings_Nástupište_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Názov priečinka grafikonu je prázdny..
        /// </summary>
        public static string FLocalSettings_Názov_priečinka_grafikonu_je_prázdny {
            get {
                return ResourceManager.GetString("FLocalSettings_Názov_priečinka_grafikonu_je_prázdny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nezadaný názov písma..
        /// </summary>
        public static string FLocalSettings_Nezadaný_názov_písma {
            get {
                return ResourceManager.GetString("FLocalSettings_Nezadaný_názov_písma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nezadaný názov stanice..
        /// </summary>
        public static string FLocalSettings_Nezadaný_názov_stanice {
            get {
                return ResourceManager.GetString("FLocalSettings_Nezadaný_názov_stanice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Všetky parametre sú povinné..
        /// </summary>
        public static string FLocalSettings_Všetky_parametre_sú_povinné {
            get {
                return ResourceManager.GetString("FLocalSettings_Všetky_parametre_sú_povinné", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadané ID stanice už má iná stanica..
        /// </summary>
        public static string FLocalSettings_Zadané_ID_stanice_už_má_iná_stanica {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadané_ID_stanice_už_má_iná_stanica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný dopravca už existuje..
        /// </summary>
        public static string FLocalSettings_Zadaný_dopravca_už_existuje {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadaný_dopravca_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný kľúč koľaje už existuje..
        /// </summary>
        public static string FLocalSettings_Zadaný_kľúč_koľaje_už_existuje {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadaný_kľúč_koľaje_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný kľúč nástupišťa už existuje..
        /// </summary>
        public static string FLocalSettings_Zadaný_kľúč_nástupišťa_už_existuje {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadaný_kľúč_nástupišťa_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tabuľka obsahuje nesprávny údaj: .
        /// </summary>
        public static string FMain_dgvTrains_DataError_Tabuľka_obsahuje_nesprávny_údaj {
            get {
                return ResourceManager.GetString("FMain_dgvTrains_DataError_Tabuľka_obsahuje_nesprávny_údaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jedna inštancia programu INISS už beží.
        ///
        ///Mám ju nútene vypnúť ?.
        /// </summary>
        public static string FMain_InissStartItemOnClick {
            get {
                return ResourceManager.GetString("FMain_InissStartItemOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mám preskočiť prechádzajúce vlaky?.
        /// </summary>
        public static string FMain_Mám_preskočiť_prechádzajúce_vlaky {
            get {
                return ResourceManager.GetString("FMain_Mám_preskočiť_prechádzajúce_vlaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Názov priečinka je prázdny..
        /// </summary>
        public static string FMain_Názov_priečinka_je_prázdny {
            get {
                return ResourceManager.GetString("FMain_Názov_priečinka_je_prázdny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nepodarilo sa spustiť vybraný program: {0}..
        /// </summary>
        public static string FMain_Nepodarilo_sa_spustiť_vybraný_program {
            get {
                return ResourceManager.GetString("FMain_Nepodarilo_sa_spustiť_vybraný_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Priečinok neobsahuje všetky potrebné dáta..
        /// </summary>
        public static string FMain_Priečinok_neobsahuje_všetky_potrebné_dáta {
            get {
                return ResourceManager.GetString("FMain_Priečinok_neobsahuje_všetky_potrebné_dáta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný V súboroch ste vykonali zmeny. Uložiť zmeny?.
        /// </summary>
        public static string FMain_Save_Changes {
            get {
                return ResourceManager.GetString("FMain_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný V uloženom zozname grafikonov sa žiaden grafikon nenachádza..
        /// </summary>
        public static string FMain_V_uloženom_zozname_grafikonov_sa_žiaden_grafikon_nenachádza {
            get {
                return ResourceManager.GetString("FMain_V_uloženom_zozname_grafikonov_sa_žiaden_grafikon_nenachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Čas konca platnosti dát má byť neskôr ako začiatok platnosti..
        /// </summary>
        public static string FNewGrafikon_Čas_konca_platnosti_dát_má_byť_neskôr_ako_začiatok_platnosti {
            get {
                return ResourceManager.GetString("FNewGrafikon_Čas_konca_platnosti_dát_má_byť_neskôr_ako_začiatok_platnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Čas konca platnosti grafikonu má byť neskôr ako začiatok platnosti..
        /// </summary>
        public static string FNewGrafikon_Čas_konca_platnosti_grafikonu_má_byť_neskôr_ako_začiatok_platnosti {
            get {
                return ResourceManager.GetString("FNewGrafikon_Čas_konca_platnosti_grafikonu_má_byť_neskôr_ako_začiatok_platnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nie je vybratá stanica..
        /// </summary>
        public static string FNewGrafikon_Nie_je_vybratá_stanica {
            get {
                return ResourceManager.GetString("FNewGrafikon_Nie_je_vybratá_stanica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nie je zadaná žiadna stanica..
        /// </summary>
        public static string FNewGrafikon_Nie_je_zadaná_žiadna_stanica {
            get {
                return ResourceManager.GetString("FNewGrafikon_Nie_je_zadaná_žiadna_stanica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Priečinok neobsahuje priečinok RAWBANK..
        /// </summary>
        public static string FNewGrafikon_Priečinok_neobsahuje_priečinok_RAWBANK {
            get {
                return ResourceManager.GetString("FNewGrafikon_Priečinok_neobsahuje_priečinok_RAWBANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaná stanica pre tento INISS už existuje..
        /// </summary>
        public static string FNewGrafikon_Zadaná_stanica_pre_tento_INISS_už_existuje {
            get {
                return ResourceManager.GetString("FNewGrafikon_Zadaná_stanica_pre_tento_INISS_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadané ID vlastnej stanice už patrí inej stanici..
        /// </summary>
        public static string FNewGrafikon_Zadané_ID_vlastnej_stanice_už_patrí_inej_stanici {
            get {
                return ResourceManager.GetString("FNewGrafikon_Zadané_ID_vlastnej_stanice_už_patrí_inej_stanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadané obdobie platnosti tejto stanice už existuje. Zvoľte iné..
        /// </summary>
        public static string FNewGrafikon_Zadané_obdobie_platnosti_tejto_stanice_už_existuje {
            get {
                return ResourceManager.GetString("FNewGrafikon_Zadané_obdobie_platnosti_tejto_stanice_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nesprávny registračný kľúč..
        /// </summary>
        public static string FRegistration_Nesprávny_registračný_kľúč {
            get {
                return ResourceManager.GetString("FRegistration_Nesprávny_registračný_kľúč", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registrácia prebehla úspešne. Zmeny sa prejavia po reštarte programu. Reštarovať teraz? .
        /// </summary>
        public static string FRegistration_Registrácia_prebehla_úspešne {
            get {
                return ResourceManager.GetString("FRegistration_Registrácia_prebehla_úspešne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registračný kľúč nebol zadaný..
        /// </summary>
        public static string FRegistration_Registračný_kľúč_nebol_zadaný {
            get {
                return ResourceManager.GetString("FRegistration_Registračný_kľúč_nebol_zadaný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Neplatný nový názov štýlu..
        /// </summary>
        public static string FRenameStyle_Neplatný_nový_názov_štýlu {
            get {
                return ResourceManager.GetString("FRenameStyle_Neplatný_nový_názov_štýlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný názov štýlu už existuje..
        /// </summary>
        public static string FRenameStyle_Zadaný_názov_štýlu_už_existuje {
            get {
                return ResourceManager.GetString("FRenameStyle_Zadaný_názov_štýlu_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný V type tabule {0} je nesprávny počet módov {1}. (Správny počet: {2})
        ///Pravdepodobne ste zabudli upraviť poradie stĺpcov..
        /// </summary>
        public static string FTableCatalog_bSave_NespravnyPocetModov {
            get {
                return ResourceManager.GetString("FTableCatalog_bSave_NespravnyPocetModov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Definované stĺpce nie sú zotriedené podľa pozície: &quot;{0}&quot;-End:{1} -&gt; &quot;{2}&quot;-End:{3}.
        /// </summary>
        public static string FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_pozície {
            get {
                return ResourceManager.GetString("FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_pozície", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Definované stĺpce nie sú zotriedené podľa zobrazovaného riadka záznamu: &quot;{0}&quot;-Line:{1} -&gt; &quot;{2}&quot;-Line:{3}.
        /// </summary>
        public static string FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_zobrazovaného_riadka_záznamu {
            get {
                return ResourceManager.GetString("FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_zobrazovaného_riadka_zázn" +
                        "amu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nie sú vyplnené všetky povinné parametre..
        /// </summary>
        public static string FTableCatalog_Nie_sú_vyplnené_všetky_povinné_parametre {
            get {
                return ResourceManager.GetString("FTableCatalog_Nie_sú_vyplnené_všetky_povinné_parametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Posledný pixel stĺpca je menší alebo rovný ako počiatočný..
        /// </summary>
        public static string FTableCatalog_Posledný_pixel_stĺpca_je_menší_alebo_rovný_ako_počiatočný {
            get {
                return ResourceManager.GetString("FTableCatalog_Posledný_pixel_stĺpca_je_menší_alebo_rovný_ako_počiatočný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraný DivType vyžaduje mať zadefinovaný {0}..
        /// </summary>
        public static string FTableCatalog_ShowErrorUnDefTab {
            get {
                return ResourceManager.GetString("FTableCatalog_ShowErrorUnDefTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybraný DivType nevyžaduje mať zadefinovaný {0}.
        ///Aj tak pokračovať ?.
        /// </summary>
        public static string FTableCatalog_ShowWarningDefTab {
            get {
                return ResourceManager.GetString("FTableCatalog_ShowWarningDefTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tabuľa ELEN môže mať max. pozíciu 512..
        /// </summary>
        public static string FTableCatalog_Tabula_ELEN_moze_mat_max_poziciu_512 {
            get {
                return ResourceManager.GetString("FTableCatalog_Tabula_ELEN_moze_mat_max_poziciu_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tento stĺpec sa prekrekrýva so stĺpcom {0}..
        /// </summary>
        public static string FTableCatalog_Tento_stĺpec_sa_prekrekrýva_so_stĺpcom {
            get {
                return ResourceManager.GetString("FTableCatalog_Tento_stĺpec_sa_prekrekrýva_so_stĺpcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný kľúč stĺpca už existuje..
        /// </summary>
        public static string FTableCatalog_Zadaný_kľúč_stĺpca_už_existuje {
            get {
                return ResourceManager.GetString("FTableCatalog_Zadaný_kľúč_stĺpca_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Texty do tabúľ sa automaticky vygenerujú podľa vlakov.
        ///Všetky zapísané texty sa zmažú.
        ///
        ///Naozaj chcete vykonať túto akciu?.
        /// </summary>
        public static string FTableText_Generate_TTexts_Info {
            get {
                return ResourceManager.GetString("FTableText_Generate_TTexts_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bol vybratý nepodporovaný typ obsahu tabule. Vyberte iný..
        /// </summary>
        public static string FTableText_Generate_TTexts_Wrong_Item {
            get {
                return ResourceManager.GetString("FTableText_Generate_TTexts_Wrong_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadajte názov..
        /// </summary>
        public static string FTabTab_Zadajte_názov {
            get {
                return ResourceManager.GetString("FTabTab_Zadajte_názov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap general {
            get {
                object obj = ResourceManager.GetObject("general", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Prerušiť.
        /// </summary>
        public static string Global_Abort {
            get {
                return ResourceManager.GetString("Global_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Zrušiť.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Ignorovať.
        /// </summary>
        public static string Global_Ignore {
            get {
                return ResourceManager.GetString("Global_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Nie.
        /// </summary>
        public static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;OK.
        /// </summary>
        public static string Global_OK {
            get {
                return ResourceManager.GetString("Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Znova.
        /// </summary>
        public static string Global_Retry {
            get {
                return ResourceManager.GetString("Global_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap global_settings {
            get {
                object obj = ResourceManager.GetObject("global-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Áno.
        /// </summary>
        public static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hammer {
            get {
                object obj = ResourceManager.GetObject("hammer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Icon).
        /// </summary>
        public static System.Drawing.Icon icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info_app {
            get {
                object obj = ResourceManager.GetObject("info-app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iniss_settings {
            get {
                object obj = ResourceManager.GetObject("iniss-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap konecna_st {
            get {
                object obj = ResourceManager.GetObject("konecna_st", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap local_settings {
            get {
                object obj = ResourceManager.GetObject("local-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap localization {
            get {
                object obj = ResourceManager.GetObject("localization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Okraje ovládacích prvkov.
        /// </summary>
        public static string NameColorSettings_Border {
            get {
                return ResourceManager.GetString("NameColorSettings_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Box.
        /// </summary>
        public static string NameColorSettings_Box {
            get {
                return ResourceManager.GetString("NameColorSettings_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tlačidlá.
        /// </summary>
        public static string NameColorSettings_Button {
            get {
                return ResourceManager.GetString("NameColorSettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zvýraznenie ovládacieho prvku alebo jeho časti.
        /// </summary>
        public static string NameColorSettings_Highlight {
            get {
                return ResourceManager.GetString("NameColorSettings_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Štítky.
        /// </summary>
        public static string NameColorSettings_Label {
            get {
                return ResourceManager.GetString("NameColorSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Značky v CheckBox a v RadioButton.
        /// </summary>
        public static string NameColorSettings_Mark {
            get {
                return ResourceManager.GetString("NameColorSettings_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Panel.
        /// </summary>
        public static string NameColorSettings_Panel {
            get {
                return ResourceManager.GetString("NameColorSettings_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap prechadza_st {
            get {
                object obj = ResourceManager.GetObject("prechadza_st", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Priečinok s týmto názvom už existuje. Zmeňte jeho názov..
        /// </summary>
        public static string Priečinok_s_týmto_názvom_už_existuje__Zmeňte_jeho_názov {
            get {
                return ResourceManager.GetString("Priečinok_s_týmto_názvom_už_existuje__Zmeňte_jeho_názov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap recent {
            get {
                object obj = ResourceManager.GetObject("recent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upraviť.
        /// </summary>
        public static string REdit {
            get {
                return ResourceManager.GetString("REdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chyba.
        /// </summary>
        public static string RError {
            get {
                return ResourceManager.GetString("RError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Informácia.
        /// </summary>
        public static string RInfo {
            get {
                return ResourceManager.GetString("RInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Otázka.
        /// </summary>
        public static string RQuestion {
            get {
                return ResourceManager.GetString("RQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aktualizácia.
        /// </summary>
        public static string RUpdate {
            get {
                return ResourceManager.GetString("RUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nová verzia programu GVDEditor ({0}) je k dispozícií.
        ///
        ///Otvoriť stránku pre stiahnutie programu?.
        /// </summary>
        public static string RUpdateInfo {
            get {
                return ResourceManager.GetString("RUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upozornenie.
        /// </summary>
        public static string RWarning {
            get {
                return ResourceManager.GetString("RWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_all {
            get {
                object obj = ResourceManager.GetObject("save_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vybranú položku nie je možné vymazať, pretože sa používa. Konflikt s:.
        /// </summary>
        public static string SelectedItemRemoveCancel {
            get {
                return ResourceManager.GetString("SelectedItemRemoveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Osobný vlak.
        /// </summary>
        public static string SetDesktopTTOs {
            get {
                return ResourceManager.GetString("SetDesktopTTOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rýchlik.
        /// </summary>
        public static string SetDesktopTTR {
            get {
                return ResourceManager.GetString("SetDesktopTTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Služobný vlak.
        /// </summary>
        public static string SetDesktopTTSl {
            get {
                return ResourceManager.GetString("SetDesktopTTSl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vlak vyššej kvality.
        /// </summary>
        public static string SetDesktopTTX {
            get {
                return ResourceManager.GetString("SetDesktopTTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zvýraznenie nedokončeného páru zátvoriek.
        /// </summary>
        public static string SetTEBraceBad {
            get {
                return ResourceManager.GetString("SetTEBraceBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zvýraznenie aktívnych zátvoriek.
        /// </summary>
        public static string SetTEBraces {
            get {
                return ResourceManager.GetString("SetTEBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Komentár.
        /// </summary>
        public static string SetTEComment {
            get {
                return ResourceManager.GetString("SetTEComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Konštanta.
        /// </summary>
        public static string SetTEConstant {
            get {
                return ResourceManager.GetString("SetTEConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Obyčajný text.
        /// </summary>
        public static string SetTEDefault {
            get {
                return ResourceManager.GetString("SetTEDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Udalosť.
        /// </summary>
        public static string SetTEEvent {
            get {
                return ResourceManager.GetString("SetTEEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Identifikátor.
        /// </summary>
        public static string SetTEIdentifier {
            get {
                return ResourceManager.GetString("SetTEIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Funkcia.
        /// </summary>
        public static string SetTEKeyword {
            get {
                return ResourceManager.GetString("SetTEKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Číslo.
        /// </summary>
        public static string SetTENumber {
            get {
                return ResourceManager.GetString("SetTENumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Znak konca riadku (prechod do ďalšieho riadku).
        /// </summary>
        public static string SetTEOnNewLine {
            get {
                return ResourceManager.GetString("SetTEOnNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Operátor.
        /// </summary>
        public static string SetTEOperator {
            get {
                return ResourceManager.GetString("SetTEOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reťazec.
        /// </summary>
        public static string SetTEString {
            get {
                return ResourceManager.GetString("SetTEString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Premenná.
        /// </summary>
        public static string SetTEVar {
            get {
                return ResourceManager.GetString("SetTEVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shortcut {
            get {
                object obj = ResourceManager.GetObject("shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shutdown {
            get {
                object obj = ResourceManager.GetObject("shutdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 0001
        ///C:&quot;Slovenský stav. diagram&quot;
        ///C:&quot;verze s přistavením u výchozích
        ///C:&quot;s tabulemi&quot;
        ///
        ///;
        ///; Defnice Designů tlačítek
        ///;
        ///P:&quot;StateDgmCtrls\\CtrlDesign&quot;
        ///{	;Bitmaps=&quot;Offset-Normal,NormalFokus,Pushed&quot;
        ///	G:&quot;Design1&quot; {S:&quot;Key&quot;=&quot;MeškanieN&quot;	S:&quot;Bitmaps&quot;=&quot;0-0,1,2&quot;	I:&quot;DefPushBtn&quot;=0	S:&quot;Class&quot;=&quot;SDCCtrlDesignBtn&quot;}
        ///	G:&quot;Design2&quot; {S:&quot;Key&quot;=&quot;KoľajN&quot;		S:&quot;Bitmaps&quot;=&quot;3-0,1,2&quot;	I:&quot;DefPushBtn&quot;=0	S:&quot;Class&quot;=&quot;SDCCtrlDesignBtn&quot;}
        ///	G:&quot;Design3&quot; {S:&quot;Key&quot;=&quot;SkryťN&quot;		S:&quot;Bitmaps&quot;=&quot;76-0,1,2&quot;	I:&quot;DefPushBtn&quot;=0	S:&quot;Class&quot;=&quot;SDCCtrlDesignBtn&quot;}
        ///	G [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string statedgmSK {
            get {
                return ResourceManager.GetString("statedgmSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nie sú vyplnené všetky povinné polia..
        /// </summary>
        public static string Tables_Nie_sú_vyplnené_všetky_povinné_polia {
            get {
                return ResourceManager.GetString("Tables_Nie_sú_vyplnené_všetky_povinné_polia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaný kľúč tabule už existuje..
        /// </summary>
        public static string Tables_Zadaný_kľúč_tabule_už_existuje {
            get {
                return ResourceManager.GetString("Tables_Zadaný_kľúč_tabule_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vychodzia_st {
            get {
                object obj = ResourceManager.GetObject("vychodzia_st", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wrench {
            get {
                object obj = ResourceManager.GetObject("wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
