//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVDEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GVDEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento program slúži na úpravu textových súborov, ktoré používa program INISS. 
        ///Program GVDEditor nie je oficiálna aplikácia spoločnosti CHAPS ani spoločnosti INPROP..
        /// </summary>
        internal static string AboutAppDescription {
            get {
                return ResourceManager.GetString("AboutAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolo zadané neplatné číslo..
        /// </summary>
        internal static string FAppSettings_Bolo_zadané_neplatné_číslo {
            get {
                return ResourceManager.GetString("FAppSettings_Bolo_zadané_neplatné_číslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektoré vykonané zmeny sa prejavia po reštarte programu. 
        ///
        ///Reštartovať program teraz?.
        /// </summary>
        internal static string FAppSettings_bSave_Click_Niektoré_zmeny_sa_prejavia_až_po_reštarte_programu {
            get {
                return ResourceManager.GetString("FAppSettings_bSave_Click_Niektoré_zmeny_sa_prejavia_až_po_reštarte_programu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrali ste typ debugovania, ktorý nie je určený pre bežných používateľov.  To môže viesť k neočakávaným následkom.
        ///
        ///Naozaj chcete použiť tento typ debugovania?.
        /// </summary>
        internal static string FAppSettings_cbDebugModeGUI_SelectedIndexChanged_Not_For_All_Users {
            get {
                return ResourceManager.GetString("FAppSettings_cbDebugModeGUI_SelectedIndexChanged_Not_For_All_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stlačte klávesovú skratku pre priradenie ku príkazu..
        /// </summary>
        internal static string FAppSettings_lShortcutHelp1 {
            get {
                return ResourceManager.GetString("FAppSettings_lShortcutHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatná klávesová skratka. Stlačte inú..
        /// </summary>
        internal static string FAppSettings_lShortcutHelp2 {
            get {
                return ResourceManager.GetString("FAppSettings_lShortcutHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmeny sa prejavia po reštarte programu..
        /// </summary>
        internal static string FAppSettings_Zmeny_sa_prejavia_po_reštarte_programu {
            get {
                return ResourceManager.GetString("FAppSettings_Zmeny_sa_prejavia_po_reštarte_programu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail je neplatný..
        /// </summary>
        internal static string FBugReport_E_mail_je_neplatný {
            get {
                return ResourceManager.GetString("FBugReport_E_mail_je_neplatný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail nebol zadaný..
        /// </summary>
        internal static string FBugReport_E_mail_nebol_zadaný {
            get {
                return ResourceManager.GetString("FBugReport_E_mail_nebol_zadaný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail sa nepodarilo odoslať: .
        /// </summary>
        internal static string FBugReport_E_mail_sa_nepodarilo_odoslať {
            get {
                return ResourceManager.GetString("FBugReport_E_mail_sa_nepodarilo_odoslať", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsah správy nebol zadaný..
        /// </summary>
        internal static string FBugReport_Obsah_správy_nebol_zadaný {
            get {
                return ResourceManager.GetString("FBugReport_Obsah_správy_nebol_zadaný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas príchodu je neskôr ako čas odchodu..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Čas_príchodu_je_neskôr_ako_čas_odchodu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Čas_príchodu_je_neskôr_ako_čas_odchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesprávny formát času odchodu..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Nesprávny_formát_času_odchodu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Nesprávny_formát_času_odchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesprávny formát času príchodu..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Nesprávny_formát_času_príchodu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Nesprávny_formát_času_príchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie je vybratá koľaj..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Nie_je_vybratá_koľaj {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Nie_je_vybratá_koľaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varianta tohto vlaku nemôže byť -1, pretože sa v zozname vlakov nachádza vlak/y s podobnými vlastnosťami..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Varianta_tohto_vlaku_nemôže_byť_Minus_1 {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Varianta_tohto_vlaku_nemôže_byť_Minus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlak nemá zadanú žiadnu stanicu..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Vlak_nemá_zadanú_žiadnu_stanicu {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Vlak_nemá_zadanú_žiadnu_stanicu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraná varianta vlaku sa už používa pri inom vlaku..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Vybraná_varianta_vlaku_sa_už_používa_pri_inom_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Vybraná_varianta_vlaku_sa_už_používa_pri_inom_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začiatok platnosti musí skôr ako koniec platnosti..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Začiatok_platnosti_musí_skôr_ako_koniec_platnosti {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Začiatok_platnosti_musí_skôr_ako_koniec_platnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte číslo vlaku..
        /// </summary>
        internal static string FEditTrain_bSave_Click_Zadajte_číslo_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_bSave_Click_Zadajte_číslo_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo vlaku sa zhoduje s iným vlakom a preto bude aj jeho radenie priradené k tomuto vlaku (Doteraz upravené radenie sa vymaže)..
        /// </summary>
        internal static string FEditTrain_Číslo_vlaku_sa_zhoduje_s_iným_vlakom_a_preto_bude_aj_jeho_radenie_priradené_k_tomuto_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_Číslo_vlaku_sa_zhoduje_s_iným_vlakom_a_preto_bude_aj_jeho_radenie_prir" +
                        "adené_k_tomuto_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátumové obmedzenie radenia obsahuje chybu: .
        /// </summary>
        internal static string FEditTrain_DateRem_radenia_obsahuje_chybu {
            get {
                return ResourceManager.GetString("FEditTrain_DateRem_radenia_obsahuje_chybu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátumové obmedzenie tohto vlaku zasahuje do vlaku {0} {1} {2} v rozmedzí 
        ///&quot;{3}&quot;.
        ///
        ///Upraviť dátumové obmedzenie popísaného vlaku?.
        /// </summary>
        internal static string FEditTrain_DateRem_zasahuje_do_ineho_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_DateRem_zasahuje_do_ineho_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplikovať vlak.
        /// </summary>
        internal static string FEditTrain_FEditTrain_Duplikovať_vlak {
            get {
                return ResourceManager.GetString("FEditTrain_FEditTrain_Duplikovať_vlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať.
        /// </summary>
        internal static string FEditTrain_FEditTrain_Pridať {
            get {
                return ResourceManager.GetString("FEditTrain_FEditTrain_Pridať", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať vlak.
        /// </summary>
        internal static string FEditTrain_FEditTrain_Pridať_vlak {
            get {
                return ResourceManager.GetString("FEditTrain_FEditTrain_Pridať_vlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebolo zadané radenie vlaku..
        /// </summary>
        internal static string FEditTrain_Nebolo_zadané_radenie_vlaku {
            get {
                return ResourceManager.GetString("FEditTrain_Nebolo_zadané_radenie_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadaný čas odchodu..
        /// </summary>
        internal static string FEditTrain_Nezadaný_čas_odchodu {
            get {
                return ResourceManager.GetString("FEditTrain_Nezadaný_čas_odchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadaný čas príchodu..
        /// </summary>
        internal static string FEditTrain_Nezadaný_čas_príchodu {
            get {
                return ResourceManager.GetString("FEditTrain_Nezadaný_čas_príchodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento vlak nemá iné varianty a preto mu bude varianta nastavená na hodnotu -1..
        /// </summary>
        internal static string FEditTrain_Tento_vlak_nemá_iné_varianty_a_preto_mu_bude_varianta_nastavená_na_hodnotu_Minus_1 {
            get {
                return ResourceManager.GetString("FEditTrain_Tento_vlak_nemá_iné_varianty_a_preto_mu_bude_varianta_nastavená_na_hod" +
                        "notu_Minus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začiatok platnosti radenia je neskôr ako jeho koniec..
        /// </summary>
        internal static string FEditTrain_Začiatok_platnosti_radenia_je_neskôr_ako_jeho_koniec {
            get {
                return ResourceManager.GetString("FEditTrain_Začiatok_platnosti_radenia_je_neskôr_ako_jeho_koniec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané dátumové obmedzenie radenia sa prekrýva s iným v období {0}..
        /// </summary>
        internal static string FEditTrain_Zadané_dátumové_obmedzenie_radenia_sa_prekrýva_s_iným_v_období {
            get {
                return ResourceManager.GetString("FEditTrain_Zadané_dátumové_obmedzenie_radenia_sa_prekrýva_s_iným_v_období", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný súbor neexistuje..
        /// </summary>
        internal static string FELISOptions_Zadaný_súbor_neexistuje {
            get {
                return ResourceManager.GetString("FELISOptions_Zadaný_súbor_neexistuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iba jeden jazyk môže byť hlavný..
        /// </summary>
        internal static string FGlobalSettings_bLanguageAdd_Click_Iba_1_jazyk_môže_byť_hlavný {
            get {
                return ResourceManager.GetString("FGlobalSettings_bLanguageAdd_Click_Iba_1_jazyk_môže_byť_hlavný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný typ vlaku sa už v zozname nachádza..
        /// </summary>
        internal static string FGlobalSettings_Click_Zadaný_typ_vlaku_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Click_Zadaný_typ_vlaku_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kľúč jazyka sa nezhoduje so žiadnym jazykom nachádzajúci sa v zvukovej banke..
        /// </summary>
        internal static string FGlobalSettings_Kľúč_jazyka_sa_nezhoduje_so_žiadnym_jazykom_nacházajúci_sa_v_zvukovej_banke {
            get {
                return ResourceManager.GetString("FGlobalSettings_Kľúč_jazyka_sa_nezhoduje_so_žiadnym_jazykom_nacházajúci_sa_v_zvuk" +
                        "ovej_banke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximálny počet typov vlakov tohto druhu je 9..
        /// </summary>
        internal static string FGlobalSettings_Maximálny_počet_typov_vlakov_tohto_druhu_je_9 {
            get {
                return ResourceManager.GetString("FGlobalSettings_Maximálny_počet_typov_vlakov_tohto_druhu_je_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo {0} nie je v intervale X &gt;= 0 a zároveň X &lt;= 480..
        /// </summary>
        internal static string FGlobalSettings_Meskanie_CisloNieJeVIntervale {
            get {
                return ResourceManager.GetString("FGlobalSettings_Meskanie_CisloNieJeVIntervale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naozaj chcete odstrániť tento grafikon ?.
        /// </summary>
        internal static string FGlobalSettings_Naozaj_chcete_odstrániť_tento_grafikon {
            get {
                return ResourceManager.GetString("FGlobalSettings_Naozaj_chcete_odstrániť_tento_grafikon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov tejto audio linky už existuje..
        /// </summary>
        internal static string FGlobalSettings_Názov_tejto_audio_linky_už_existuje {
            get {
                return ResourceManager.GetString("FGlobalSettings_Názov_tejto_audio_linky_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebola zadaná skratka typu vlaku..
        /// </summary>
        internal static string FGlobalSettings_Nebola_zadaná_skratka_typu_vlaku {
            get {
                return ResourceManager.GetString("FGlobalSettings_Nebola_zadaná_skratka_typu_vlaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neboli vyplnené všetky polia..
        /// </summary>
        internal static string FGlobalSettings_Neboli_vyplnené_všetky_polia {
            get {
                return ResourceManager.GetString("FGlobalSettings_Neboli_vyplnené_všetky_polia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Táto hodnota sa už v zozname nachádza..
        /// </summary>
        internal static string FGlobalSettings_Táto_hodnota_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Táto_hodnota_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný typ vlaku sa už v zozname nachádza..
        /// </summary>
        internal static string FGlobalSettings_Vybraný_typ_vlaku_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Vybraný_typ_vlaku_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný jazyk sa sa už v zozname nachádza..
        /// </summary>
        internal static string FGlobalSettings_Zadaný_jazyk_sa_sa_už_v_zozname_nachádza {
            get {
                return ResourceManager.GetString("FGlobalSettings_Zadaný_jazyk_sa_sa_už_v_zozname_nachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie sú zadané údaje pre import..
        /// </summary>
        internal static string FImportData_Nie_sú_zadané_údaje_pre_import {
            get {
                return ResourceManager.GetString("FImportData_Nie_sú_zadané_údaje_pre_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koľaj .
        /// </summary>
        internal static string FLocalSettings_Koľaj_ {
            get {
                return ResourceManager.GetString("FLocalSettings_Koľaj_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nástupište .
        /// </summary>
        internal static string FLocalSettings_Nástupište_ {
            get {
                return ResourceManager.GetString("FLocalSettings_Nástupište_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov priečinka grafikonu je prázdny..
        /// </summary>
        internal static string FLocalSettings_Názov_priečinka_grafikonu_je_prázdny {
            get {
                return ResourceManager.GetString("FLocalSettings_Názov_priečinka_grafikonu_je_prázdny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadaný názov písma..
        /// </summary>
        internal static string FLocalSettings_Nezadaný_názov_písma {
            get {
                return ResourceManager.GetString("FLocalSettings_Nezadaný_názov_písma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadaný názov stanice..
        /// </summary>
        internal static string FLocalSettings_Nezadaný_názov_stanice {
            get {
                return ResourceManager.GetString("FLocalSettings_Nezadaný_názov_stanice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všetky parametre sú povinné..
        /// </summary>
        internal static string FLocalSettings_Všetky_parametre_sú_povinné {
            get {
                return ResourceManager.GetString("FLocalSettings_Všetky_parametre_sú_povinné", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané ID stanice už má iná stanica..
        /// </summary>
        internal static string FLocalSettings_Zadané_ID_stanice_už_má_iná_stanica {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadané_ID_stanice_už_má_iná_stanica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný dopravca už existuje..
        /// </summary>
        internal static string FLocalSettings_Zadaný_dopravca_už_existuje {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadaný_dopravca_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný kľúč koľaje už existuje..
        /// </summary>
        internal static string FLocalSettings_Zadaný_kľúč_koľaje_už_existuje {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadaný_kľúč_koľaje_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný kľúč nástupišťa už existuje..
        /// </summary>
        internal static string FLocalSettings_Zadaný_kľúč_nástupišťa_už_existuje {
            get {
                return ResourceManager.GetString("FLocalSettings_Zadaný_kľúč_nástupišťa_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľka obsahuje nesprávny údaj: .
        /// </summary>
        internal static string FMain_dgvTrains_DataError_Tabuľka_obsahuje_nesprávny_údaj {
            get {
                return ResourceManager.GetString("FMain_dgvTrains_DataError_Tabuľka_obsahuje_nesprávny_údaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedna inštancia programu INISS už beží.
        ///
        ///Mám ju nútene vypnúť ?.
        /// </summary>
        internal static string FMain_InissStartItemOnClick {
            get {
                return ResourceManager.GetString("FMain_InissStartItemOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mám preskočiť prechádzajúce vlaky?.
        /// </summary>
        internal static string FMain_Mám_preskočiť_prechádzajúce_vlaky {
            get {
                return ResourceManager.GetString("FMain_Mám_preskočiť_prechádzajúce_vlaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov priečinka je prázdny..
        /// </summary>
        internal static string FMain_Názov_priečinka_je_prázdny {
            get {
                return ResourceManager.GetString("FMain_Názov_priečinka_je_prázdny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodarilo sa spustiť vybraný program: {0}..
        /// </summary>
        internal static string FMain_Nepodarilo_sa_spustiť_vybraný_program {
            get {
                return ResourceManager.GetString("FMain_Nepodarilo_sa_spustiť_vybraný_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priečinok neobsahuje všetky potrebné dáta..
        /// </summary>
        internal static string FMain_Priečinok_neobsahuje_všetky_potrebné_dáta {
            get {
                return ResourceManager.GetString("FMain_Priečinok_neobsahuje_všetky_potrebné_dáta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V súboroch ste vykonali zmeny. Uložiť zmeny?.
        /// </summary>
        internal static string FMain_Save_Changes {
            get {
                return ResourceManager.GetString("FMain_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V uloženom zozname grafikonov sa žiaden grafikon nenachádza..
        /// </summary>
        internal static string FMain_V_uloženom_zozname_grafikonov_sa_žiaden_grafikon_nenachádza {
            get {
                return ResourceManager.GetString("FMain_V_uloženom_zozname_grafikonov_sa_žiaden_grafikon_nenachádza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas konca platnosti dát má byť neskôr ako začiatok platnosti..
        /// </summary>
        internal static string FNewGrafikon_Čas_konca_platnosti_dát_má_byť_neskôr_ako_začiatok_platnosti {
            get {
                return ResourceManager.GetString("FNewGrafikon_Čas_konca_platnosti_dát_má_byť_neskôr_ako_začiatok_platnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas konca platnosti grafikonu má byť neskôr ako začiatok platnosti..
        /// </summary>
        internal static string FNewGrafikon_Čas_konca_platnosti_grafikonu_má_byť_neskôr_ako_začiatok_platnosti {
            get {
                return ResourceManager.GetString("FNewGrafikon_Čas_konca_platnosti_grafikonu_má_byť_neskôr_ako_začiatok_platnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie je vybratá stanica..
        /// </summary>
        internal static string FNewGrafikon_Nie_je_vybratá_stanica {
            get {
                return ResourceManager.GetString("FNewGrafikon_Nie_je_vybratá_stanica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie je zadaná žiadna stanica..
        /// </summary>
        internal static string FNewGrafikon_Nie_je_zadaná_žiadna_stanica {
            get {
                return ResourceManager.GetString("FNewGrafikon_Nie_je_zadaná_žiadna_stanica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priečinok neobsahuje priečinok RAWBANK..
        /// </summary>
        internal static string FNewGrafikon_Priečinok_neobsahuje_priečinok_RAWBANK {
            get {
                return ResourceManager.GetString("FNewGrafikon_Priečinok_neobsahuje_priečinok_RAWBANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaná stanica pre tento INISS už existuje..
        /// </summary>
        internal static string FNewGrafikon_Zadaná_stanica_pre_tento_INISS_už_existuje {
            get {
                return ResourceManager.GetString("FNewGrafikon_Zadaná_stanica_pre_tento_INISS_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané ID vlastnej stanice už patrí inej stanici..
        /// </summary>
        internal static string FNewGrafikon_Zadané_ID_vlastnej_stanice_už_patrí_inej_stanici {
            get {
                return ResourceManager.GetString("FNewGrafikon_Zadané_ID_vlastnej_stanice_už_patrí_inej_stanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané obdobie platnosti tejto stanice už existuje. Zvoľte iné..
        /// </summary>
        internal static string FNewGrafikon_Zadané_obdobie_platnosti_tejto_stanice_už_existuje {
            get {
                return ResourceManager.GetString("FNewGrafikon_Zadané_obdobie_platnosti_tejto_stanice_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesprávny registračný kľúč..
        /// </summary>
        internal static string FRegistration_Nesprávny_registračný_kľúč {
            get {
                return ResourceManager.GetString("FRegistration_Nesprávny_registračný_kľúč", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrácia prebehla úspešne. Zmeny sa prejavia po reštarte programu. Reštarovať teraz? .
        /// </summary>
        internal static string FRegistration_Registrácia_prebehla_úspešne {
            get {
                return ResourceManager.GetString("FRegistration_Registrácia_prebehla_úspešne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registračný kľúč nebol zadaný..
        /// </summary>
        internal static string FRegistration_Registračný_kľúč_nebol_zadaný {
            get {
                return ResourceManager.GetString("FRegistration_Registračný_kľúč_nebol_zadaný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný nový názov štýlu..
        /// </summary>
        internal static string FRenameStyle_Neplatný_nový_názov_štýlu {
            get {
                return ResourceManager.GetString("FRenameStyle_Neplatný_nový_názov_štýlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný názov štýlu už existuje..
        /// </summary>
        internal static string FRenameStyle_Zadaný_názov_štýlu_už_existuje {
            get {
                return ResourceManager.GetString("FRenameStyle_Zadaný_názov_štýlu_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V type tabule {0} je nesprávny počet módov {1}. (Správny počet: {2})
        ///Pravdepodobne ste zabudli upraviť poradie stĺpcov..
        /// </summary>
        internal static string FTableCatalog_bSave_NespravnyPocetModov {
            get {
                return ResourceManager.GetString("FTableCatalog_bSave_NespravnyPocetModov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definované stĺpce nie sú zotriedené podľa pozície: &quot;{0}&quot;-End:{1} -&gt; &quot;{2}&quot;-End:{3}.
        /// </summary>
        internal static string FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_pozície {
            get {
                return ResourceManager.GetString("FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_pozície", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definované stĺpce nie sú zotriedené podľa zobrazovaného riadka záznamu: &quot;{0}&quot;-Line:{1} -&gt; &quot;{2}&quot;-Line:{3}.
        /// </summary>
        internal static string FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_zobrazovaného_riadka_záznamu {
            get {
                return ResourceManager.GetString("FTableCatalog_Definované_stĺpce_nie_sú_zotriedené_podľa_zobrazovaného_riadka_zázn" +
                        "amu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie sú vyplnené všetky povinné parametre..
        /// </summary>
        internal static string FTableCatalog_Nie_sú_vyplnené_všetky_povinné_parametre {
            get {
                return ResourceManager.GetString("FTableCatalog_Nie_sú_vyplnené_všetky_povinné_parametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posledný pixel stĺpca je menší alebo rovný ako počiatočný..
        /// </summary>
        internal static string FTableCatalog_Posledný_pixel_stĺpca_je_menší_alebo_rovný_ako_počiatočný {
            get {
                return ResourceManager.GetString("FTableCatalog_Posledný_pixel_stĺpca_je_menší_alebo_rovný_ako_počiatočný", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný DivType vyžaduje mať zadefinovaný {0}..
        /// </summary>
        internal static string FTableCatalog_ShowErrorUnDefTab {
            get {
                return ResourceManager.GetString("FTableCatalog_ShowErrorUnDefTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný DivType nevyžaduje mať zadefinovaný {0}.
        ///Aj tak pokračovať ?.
        /// </summary>
        internal static string FTableCatalog_ShowWarningDefTab {
            get {
                return ResourceManager.GetString("FTableCatalog_ShowWarningDefTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľa ELEN môže mať max. pozíciu 512..
        /// </summary>
        internal static string FTableCatalog_Tabula_ELEN_moze_mat_max_poziciu_512 {
            get {
                return ResourceManager.GetString("FTableCatalog_Tabula_ELEN_moze_mat_max_poziciu_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento stĺpec sa prekrekrýva so stĺpcom {0}..
        /// </summary>
        internal static string FTableCatalog_Tento_stĺpec_sa_prekrekrýva_so_stĺpcom {
            get {
                return ResourceManager.GetString("FTableCatalog_Tento_stĺpec_sa_prekrekrýva_so_stĺpcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný kľúč stĺpca už existuje..
        /// </summary>
        internal static string FTableCatalog_Zadaný_kľúč_stĺpca_už_existuje {
            get {
                return ResourceManager.GetString("FTableCatalog_Zadaný_kľúč_stĺpca_už_existuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texty do tabúľ sa automaticky vygenerujú podľa vlakov.
        ///Všetky zapísané texty sa zmažú.
        ///
        ///Naozaj chcete vykonať túto akciu?.
        /// </summary>
        internal static string FTableText_Generate_TTexts_Info {
            get {
                return ResourceManager.GetString("FTableText_Generate_TTexts_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bol vybratý nepodporovaný typ obsahu tabule. Vyberte iný..
        /// </summary>
        internal static string FTableText_Generate_TTexts_Wrong_Item {
            get {
                return ResourceManager.GetString("FTableText_Generate_TTexts_Wrong_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte názov..
        /// </summary>
        internal static string FTabTab_Zadajte_názov {
            get {
                return ResourceManager.GetString("FTabTab_Zadajte_názov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Prerušiť.
        /// </summary>
        internal static string Global_Abort {
            get {
                return ResourceManager.GetString("Global_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zrušiť.
        /// </summary>
        internal static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignorovať.
        /// </summary>
        internal static string Global_Ignore {
            get {
                return ResourceManager.GetString("Global_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nie.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Global_OK {
            get {
                return ResourceManager.GetString("Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Znova.
        /// </summary>
        internal static string Global_Retry {
            get {
                return ResourceManager.GetString("Global_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Áno.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gvd {
            get {
                object obj = ResourceManager.GetObject("gvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okraje ovládacích prvkov.
        /// </summary>
        internal static string NameColorSettings_Border {
            get {
                return ResourceManager.GetString("NameColorSettings_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string NameColorSettings_Box {
            get {
                return ResourceManager.GetString("NameColorSettings_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tlačidlá.
        /// </summary>
        internal static string NameColorSettings_Button {
            get {
                return ResourceManager.GetString("NameColorSettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýraznenie ovládacieho prvku alebo jeho časti.
        /// </summary>
        internal static string NameColorSettings_Highlight {
            get {
                return ResourceManager.GetString("NameColorSettings_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Štítky.
        /// </summary>
        internal static string NameColorSettings_Label {
            get {
                return ResourceManager.GetString("NameColorSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Značky v CheckBox a v RadioButton.
        /// </summary>
        internal static string NameColorSettings_Mark {
            get {
                return ResourceManager.GetString("NameColorSettings_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string NameColorSettings_Panel {
            get {
                return ResourceManager.GetString("NameColorSettings_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priečinok s týmto názvom už existuje. Zmeňte jeho názov..
        /// </summary>
        internal static string Priečinok_s_týmto_názvom_už_existuje__Zmeňte_jeho_názov {
            get {
                return ResourceManager.GetString("Priečinok_s_týmto_názvom_už_existuje__Zmeňte_jeho_názov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť.
        /// </summary>
        internal static string REdit {
            get {
                return ResourceManager.GetString("REdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string RError {
            get {
                return ResourceManager.GetString("RError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informácia.
        /// </summary>
        internal static string RInfo {
            get {
                return ResourceManager.GetString("RInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka.
        /// </summary>
        internal static string RQuestion {
            get {
                return ResourceManager.GetString("RQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizácia.
        /// </summary>
        internal static string RUpdate {
            get {
                return ResourceManager.GetString("RUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová verzia programu GVDEditor ({0}) je k dispozícií.
        ///
        ///Otvoriť stránku pre stiahnutie programu?.
        /// </summary>
        internal static string RUpdateInfo {
            get {
                return ResourceManager.GetString("RUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornenie.
        /// </summary>
        internal static string RWarning {
            get {
                return ResourceManager.GetString("RWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybranú položku nie je možné vymazať, pretože sa používa. Konflikt s:.
        /// </summary>
        internal static string SelectedItemRemoveCancel {
            get {
                return ResourceManager.GetString("SelectedItemRemoveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobný vlak.
        /// </summary>
        internal static string SetDesktopTTOs {
            get {
                return ResourceManager.GetString("SetDesktopTTOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rýchlik.
        /// </summary>
        internal static string SetDesktopTTR {
            get {
                return ResourceManager.GetString("SetDesktopTTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Služobný vlak.
        /// </summary>
        internal static string SetDesktopTTSl {
            get {
                return ResourceManager.GetString("SetDesktopTTSl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlak vyššej kvality.
        /// </summary>
        internal static string SetDesktopTTX {
            get {
                return ResourceManager.GetString("SetDesktopTTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýraznenie nedokončeného páru zátvoriek.
        /// </summary>
        internal static string SetTEBraceBad {
            get {
                return ResourceManager.GetString("SetTEBraceBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýraznenie aktívnych zátvoriek.
        /// </summary>
        internal static string SetTEBraces {
            get {
                return ResourceManager.GetString("SetTEBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentár.
        /// </summary>
        internal static string SetTEComment {
            get {
                return ResourceManager.GetString("SetTEComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konštanta.
        /// </summary>
        internal static string SetTEConstant {
            get {
                return ResourceManager.GetString("SetTEConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obyčajný text.
        /// </summary>
        internal static string SetTEDefault {
            get {
                return ResourceManager.GetString("SetTEDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udalosť.
        /// </summary>
        internal static string SetTEEvent {
            get {
                return ResourceManager.GetString("SetTEEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikátor.
        /// </summary>
        internal static string SetTEIdentifier {
            get {
                return ResourceManager.GetString("SetTEIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcia.
        /// </summary>
        internal static string SetTEKeyword {
            get {
                return ResourceManager.GetString("SetTEKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        internal static string SetTENumber {
            get {
                return ResourceManager.GetString("SetTENumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znak konca riadku (prechod do ďalšieho riadku).
        /// </summary>
        internal static string SetTEOnNewLine {
            get {
                return ResourceManager.GetString("SetTEOnNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operátor.
        /// </summary>
        internal static string SetTEOperator {
            get {
                return ResourceManager.GetString("SetTEOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reťazec.
        /// </summary>
        internal static string SetTEString {
            get {
                return ResourceManager.GetString("SetTEString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premenná.
        /// </summary>
        internal static string SetTEVar {
            get {
                return ResourceManager.GetString("SetTEVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001
        ///C:&quot;Slovenský stav. diagram&quot;
        ///C:&quot;verze s přistavením u výchozích
        ///C:&quot;s tabulemi&quot;
        ///
        ///;
        ///; Defnice Designů tlačítek
        ///;
        ///P:&quot;StateDgmCtrls\\CtrlDesign&quot;
        ///{	;Bitmaps=&quot;Offset-Normal,NormalFokus,Pushed&quot;
        ///	G:&quot;Design1&quot; {S:&quot;Key&quot;=&quot;MeškanieN&quot;	S:&quot;Bitmaps&quot;=&quot;0-0,1,2&quot;	I:&quot;DefPushBtn&quot;=0	S:&quot;Class&quot;=&quot;SDCCtrlDesignBtn&quot;}
        ///	G:&quot;Design2&quot; {S:&quot;Key&quot;=&quot;KoľajN&quot;		S:&quot;Bitmaps&quot;=&quot;3-0,1,2&quot;	I:&quot;DefPushBtn&quot;=0	S:&quot;Class&quot;=&quot;SDCCtrlDesignBtn&quot;}
        ///	G:&quot;Design3&quot; {S:&quot;Key&quot;=&quot;SkryťN&quot;		S:&quot;Bitmaps&quot;=&quot;76-0,1,2&quot;	I:&quot;DefPushBtn&quot;=0	S:&quot;Class&quot;=&quot;SDCCtrlDesignBtn&quot;}
        ///	G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statedgmSK {
            get {
                return ResourceManager.GetString("statedgmSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie sú vyplnené všetky povinné polia..
        /// </summary>
        internal static string Tables_Nie_sú_vyplnené_všetky_povinné_polia {
            get {
                return ResourceManager.GetString("Tables_Nie_sú_vyplnené_všetky_povinné_polia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný kľúč tabule už existuje..
        /// </summary>
        internal static string Tables_Zadaný_kľúč_tabule_už_existuje {
            get {
                return ResourceManager.GetString("Tables_Zadaný_kľúč_tabule_už_existuje", resourceCulture);
            }
        }
    }
}
